/**
 * Generate Supabase Types
 * Last Updated: 2025-01-16
 * 
 * Script to generate TypeScript types from Supabase database schema.
 */

import { execSync } from 'child_process'
import { writeFileSync } from 'fs'
import { join } from 'path'

/**
 * Generate types using Supabase CLI
 */
function generateTypes() {
  try {
    // Generate types using Supabase CLI
    console.log('Generating Supabase types...')
    execSync('supabase gen types typescript --local > types.temp.ts', {
      stdio: 'inherit'
    })

    // Read generated types
    const types = require('../types.temp.ts')

    // Create type file content
    const content = `/**
 * Generated Supabase Types
 * Last Updated: ${new Date().toISOString()}
 * 
 * DO NOT EDIT - This file is automatically generated by the generate-types script.
 */

export type Database = ${JSON.stringify(types.Database, null, 2)}
`

    // Write to final location
    const typesPath = join(__dirname, '..', 'app', 'lib', 'supabase', 'database.types.ts')
    writeFileSync(typesPath, content)

    // Clean up temp file
    execSync('rm types.temp.ts')

    console.log('Successfully generated Supabase types!')
  } catch (error) {
    console.error('Failed to generate types:', error)
    process.exit(1)
  }
}

// Run if called directly
if (require.main === module) {
  generateTypes()
} 